### ISSUE TITLE
we need to add node documentation to this as well

### ISSUE THREAD

**Issue by noahehall** [CMTegner/mdn#2]
wouldnt that be awesome?

**Comment by CMTegner** [comment]
Hi Noah!

What kind of documentation were you thinking of? How to use `mdn` in a node app? Or how to install node so that you can use `mdn`?

**Comment by noahehall** [comment]
If we could somehow add https://nodejs.org/api/

**Comment by noahehall** [comment]
i may be able to contribute after the new year

**Comment by CMTegner** [comment]
Ah, now I understand! You want to be able to not only search mdn, but also the node docs (and possibly others). I'm not sure how this would work in practice, but I'd be happy to discuss any suggestions.

**Comment by markbrown4** [comment]
@noahehall doesn't make sense in a package named `mdn`, this looks like what you're after:
https://www.npmjs.com/package/node-search

**Comment by CMTegner** [comment]
Great, a solution exists!
