### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by ianchanning** [CMTegner/mdn#3]
If I try installing this on Ubuntu I no longer get any output.

It might be because you use <http://mdn.io> instead of <https://mdn.io>.

Anyway I switched to adding a function to my `.bashrc`:

``` bash
function mdn() {
    open https://mdn.io/$1
}
export -f mdn
```

This works in a similar way `mdn map` will open a browser to the same place as this library.

**Comment by CMTegner** [comment]
Thanks! Fixed in https://github.com/CMTegner/mdn/commit/7e8886024e4d0bddc72f5fc0db691711fbdf741b and published in v1.0.2.
